fix: enable back linting (we depend on the sharp-libvips build)
so this should be fine

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,7 +1,10 @@
 name: CI
+
 on:
-  - push
-  - pull_request
+  push:
+    tags:
+      - "v*"
+
 permissions: {}
 jobs:
   lint:
@@ -13,15 +16,15 @@ jobs:
       - uses: actions/setup-node@v5
         with:
           node-version: "24"
-      # - run: npm install --ignore-scripts
-      # - name: Make sure we don't build and can't publish
-      #   if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
-      #   run: |
-      #     echo "Error: This workflow should only run on version tags (refs/tags/v*)"
-      #     exit 1
-      # - run: npm run lint-cpp
-      # - run: npm run lint-js
-      # - run: npm run lint-types
+      - run: npm install --ignore-scripts
+      - name: Make sure we don't build and can't publish
+        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
+        run: |
+          echo "Error: This workflow should only run on version tags (refs/tags/v*)"
+          exit 1
+      - run: npm run lint-cpp
+      - run: npm run lint-js
+      - run: npm run lint-types
   build-native:
     permissions:
       contents: read
